name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  PR-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/create-or-update-comment@v2
        id: couc
        with:
          body: âŒ› Deploy Preview - Build in Progress
          issue-number: ${{ github.event.number }}

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - run: npm ci && npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: pr/${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/create-or-update-comment@v2
        with:
          body: âœ”ï¸ Preview Ready - https://yashash1511.github.io/pr/${{ github.event.number }} !
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace

      - if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: âŒ Preview failed ! ğŸ” Inspect the [deploy log](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) !
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace
